### ISSUE TITLE
FatFs from upstream is updated.

### ISSUE THREAD

**Issue by leaveye** [pabigot/FatFs#2]
R0.13b released in April 7, 2018.

please update, thanks.

**Comment by pabigot** [comment]
I've done the update but don't take that as a promise this mirror will be maintained.  It exists solely so when I use fatfs every couple years I can easily review the changes.

**Comment by leaveye** [comment]
Thanks, its just fine. I use this repo to trace the change sets instead of
the official zip files.

2018-04-11 18:21 GMT+08:00 Peter A. Bigot <notifications@github.com>:
